version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: direcional_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: direcional_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d direcional_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: direcional_api
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/direcional_db
      SECRET_KEY: your-secret-key-change-this-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
